CONFIG_DIR = "/etc/protoplaster"
REPORTS_DIR = "/var/lib/protoplaster/reports"
ARTIFACTS_DIR = "/var/lib/protoplaster/artifacts"
LOCAL_DEVICE_NAME = "Local device"
LOCAL_DEVICE_HOST = "localhost"
WEBUI_POLLING_INTERVAL = 1  # seconds
SERVE_IP = "0.0.0.0"
REMOTE_RUN_TRIGGER_TIMEOUT = 10  # seconds
PROTOPLASTER = "protoplaster"
